apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
      - name: chatapp
        image: durkeshwaran1103/chatapp:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
